---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_de4ea19a575e
          env:
            - name: http_proxy
              value: "http://krmp-proxy.9rum.cc:3128"
            - name: https_proxy
              value: "http://krmp-proxy.9rum.cc:3128"
            - name: no_proxy
              value: "localhost,127.0.0.1,127.0.0.0/8,.9rum.cc,.kakao.com,.krampoline.com"
          resources:
            requests:
              memory: 1Gi
          volumeMounts:
          - name: app
            subPath: application.yml
            mountPath: /usr/src/application.yml
      volumes:
      - name: app
        configMap:
          items:
            - key: application.yml
              path: application.yml
          name: app-dddfmm8d8h
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    # selector 가 app name 에 맞도록 주위해주세요.
    app: backend
  ports:
    - port: 8080
      targetPort: 8080