---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: krmp-d2hub-idock.9rum.cc/goorm/mysql:8.0.39
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: chlwjdgma123
            - name: MYSQL_DATABASE
              value: startupvalley_db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
              subPath: mysql
          resources:
            limits:
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 3306
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  clusterIP: None # Headless
  selector:
    app: mysql
  ports:
    - port: 3306